### ISSUE TITLE
请教,推流时网断了,怎么重连

### ISSUE THREAD

**Issue by youngyunxing** [chenliming777/LMLiveStreaming#1]
如题,谢谢

**Comment by chenliming777** [comment]
这个我认为librtmp内部自己处理了，因为我自己测试当发送数据时，网络突然断了，然后会卡在发送里面，网络连接成功后可以继续发送。你先测试一下吧，我也在研究研究

**Comment by youngyunxing** [comment]
谢谢,您的代码确实可以自动重连,小概率崩溃.我看了下librtmp,有一个自动重连的函数RTMP_ReconnectStream,但是,似乎没有地方调用
