### ISSUE TITLE
连续切换推流断流会发生异常

### ISSUE THREAD

**Issue by zhaoxiaobao** [chenliming777/LMLiveStreaming#10]
**bug场景复现**：持续点击开始关闭直播按钮时推流地址会发生异常
**错误异常如下：**
`libsystem_kernel.dylib`mach_msg_trap:
    0x180db4fd0 <+0>: movn   x16, #0x1e
    0x180db4fd4 <+4>: svc    #0x80
->  0x180db4fd8 <+8>: ret  `
**应用场景：**
直播时候切换到后台需要停止推流，然后再切换到前台需要再次推流。
感觉是socket问题。
希望作者能看看($ ^ $)

**Comment by chenliming777** [comment]
会看的

**Comment by chenliming777** [comment]
你测一下  1.6.4版本  刚刚更新的 看看是否有问题  随时沟通吧
