### ISSUE TITLE
麦克风被占用了，恢复不过来了。

### ISSUE THREAD

**Issue by zhaoxiaobao** [chenliming777/LMLiveStreaming#12]
在推流过程中，微信视频，麦克风会被抢占，关闭微信返回程序时，推流音频没有了。你们咋处理的？销毁LFLiveSession，再创建一个吗？

**Comment by chenliming777** [comment]
你指的是音频没有了  只传输视频呢 。 还是指不上传了。如果是不上传了，你查看一下最新提交(https://github.com/LaiFengiOS/LFLiveKit  后续状态烦请告知)

**Comment by zhaoxiaobao** [comment]
只传输视频流，没有音频流，我觉得你在接受到AVAudioSessionInterruptionNotification 可以处理下，看能不能恢复过来。

**Comment by chenliming777** [comment]
我并没有复现  但我还是加了保护机制，你更新1.7.1测一下吧,结果告诉一下哦

**Comment by chenliming777** [comment]
我复现了   并且解决了  你看下提交日志吧  加了2行代码
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
    [[AVAudioSession sharedInstance] setActive:YES error:nil];
