### ISSUE TITLE
lflivekit  收不到 错误码

### ISSUE THREAD

**Issue by Demonsword27** [chenliming777/LMLiveStreaming#14]
在你这个项目中 在代理方法中 ，我收不到lflivekit的错误提示  - (void)liveSession:(nullable LFLiveSession*)session errorCode:(LFLiveSocketErrorCode)errorCode;   不知道是为什么  作者你试过吗  比如随便填一个地址

**Comment by chenliming777** [comment]
session的debug设置为YES
