### ISSUE TITLE
There is an 8px black border at the right edge of encoded video with default setting.

### ISSUE THREAD

**Issue by bcse** [chenliming777/LMLiveStreaming#2]
When output video resolution is 360x640, there is an 8px black border at the right edge.
Change video resolution to 368x640, the issue is gone.

**Comment by chenliming777** [comment]
thanks， Is the width to be divisible by 16

**Comment by chenliming777** [comment]
Update later

**Comment by bcse** [comment]
Did you mean you will update the resolution to 368x640?

**Comment by chenliming777** [comment]
yes
