### ISSUE TITLE
希望添加一个滤镜功能！

### ISSUE THREAD

**Issue by xxfenxx** [chenliming777/LMLiveStreaming#4]
项目中经常会用到滤镜的功能，希望可以实现自定义滤镜的功能！如果是给yuv或RGB像素数据添加滤镜，请问在当前的项目中最好是在哪一块修改呢，谢谢！！！

**Comment by chenliming777** [comment]
目前支持滤镜功能的，在videoCapture里面，用的GPUImage实现的，可以随意修改的

**Comment by xxfenxx** [comment]
已经找到修改的滤镜的地方，功能确实强大啊！！！
