### ISSUE TITLE
下载openss (openss.org)  应该是 openssl (openssl.org) ?

### ISSUE THREAD

**Issue by xxfenxx** [chenliming777/LMLiveStreaming#5]
笔误吗？

**Comment by xxfenxx** [comment]
安装服务器出错！
疑问：
1.配置服务器的步骤可以详细点吗，谢谢！
2.电脑系统环境是什么？
3.文件的下载地址希望可以直接超链接过去，已经下载的对应的版本

以下是执行make报错信息：
/Users/hanzimacbook-pro/Desktop/rtmp_server/arut-nginx-rtmp-module/ngx_rtmp_core_module.c:548:46: error: 
      operand of type 'ngx_sockaddr_t' where arithmetic or pointer type is required
        if (ngx_memcmp(ls[i].sockaddr + off, u.sockaddr + off, len) != 0) {
                                             ^~~~~~~~~~
src/core/ngx_string.h:144:73: note: expanded from macro 'ngx_memcmp'
#define ngx_memcmp(s1, s2, n)  memcmp((const char _) s1, (const char *) s2, n)
                                                                        ^~
/Users/hanzimacbook-pro/Desktop/rtmp_server/arut-nginx-rtmp-module/ngx_rtmp_core_module.c:568:30: error: 
      passing 'ngx_sockaddr_t' to parameter of incompatible type 'const void *'
    ngx_memcpy(ls->sockaddr, u.sockaddr, u.socklen);
                             ^~~~~~~~~~
src/core/ngx_string.h:102:54: note: expanded from macro 'ngx_memcpy'
#define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
                                                     ^~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/secure/_string.h:65:33: note: 
      expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^~~
2 errors generated.
make[1]: *_\* [objs/addon/arut-nginx-rtmp-module/ngx_rtmp_core_module.o] Error 1
make: **\* [build] Error 2

**Comment by xxfenxx** [comment]
推流报：ERROR: RTMP_Connect0, failed to connect socket. 61 (Connection refused)
但是用ffmpeg命令没问题

**Comment by chenliming777** [comment]
环境是OSX   版本：10.11.3，推流报错那个我周一调一下

**Comment by chenliming777** [comment]
您这个推流可以试一下其它rtmp服务器，好多线上的，看看好用不

**Comment by chenliming777** [comment]
这个问题不知道你那边进展怎么样了，我这里不能复现，暂时关了，有问题再提吧
