### ISSUE TITLE
设置压缩等级为baseline时,十分模糊,但是videocore好像没什么变化

### ISSUE THREAD

**Issue by youngyunxing** [chenliming777/LMLiveStreaming#8]
请问这是什么原因,谢谢

**Comment by chenliming777** [comment]
你是修改的源码  不是调用接口对吧

**Comment by youngyunxing** [comment]
嗯,我看您写的代码,通俗易懂,所以拿来研究了,...

**Comment by youngyunxing** [comment]
找到原因了:具体为什么我也不清楚.但是修改一下代码可解决
//第一处
- (void)initCompressionSession{
  OSStatus status = VTCompressionSessionCreate(NULL, _config.videoSize.width, _config.videoSize.height, kCMVideoCodecType_H264, NULL, NULL, NULL, didCompressBuffer, (__bridge void *)(self),  &_compressionSession);
  
  VTSessionSetProperty(_compressionSession, kVTCompressionPropertyKey_RealTime, kCFBooleanTrue);
  VTSessionSetProperty(_compressionSession, kVTCompressionPropertyKey_ProfileLevel, kVTProfileLevel_H264_Baseline_AutoLevel);
  VTCompressionSessionPrepareToEncodeFrames(_compressionSession);
  }

//第二处
- (void)encodeVideoData:(CMSampleBufferRef)sampleBuffer timeStamp:(uint64_t)timeStamp{
  CVImageBufferRef imageBuffer = (CVImageBufferRef)CMSampleBufferGetImageBuffer(sampleBuffer);
  CMTime presentationTimeStamp =  CMSampleBufferGetOutputPresentationTimeStamp(sampleBuffer);
  VTEncodeInfoFlags flags;
  OSStatus statusCode = VTCompressionSessionEncodeFrame(_compressionSession,
                                                        imageBuffer,
                                                        presentationTimeStamp,
                                                        kCMTimeInvalid,
                                                        NULL, NULL, &flags);  
  }

timestamp用最外面的,不用里面生成的

**Comment by chenliming777** [comment]
第一处我还能理解  第二处时间戳这个不知道为什么要修改  😄

**Comment by youngyunxing** [comment]
Timestamp应该不算原因,我看了一下,差距不大,相差1ms

**Comment by chenliming777** [comment]
哦哦

**Comment by chenliming777** [comment]
那就是  修改baseLine的时候  需要修改realTime为YES

**Comment by youngyunxing** [comment]
经过最终的检查发现:
//    status = VTSessionSetProperty(compressionSession, kVTCompressionPropertyKey_H264EntropyMode, kVTH264EntropyMode_CABAC);
只需注释掉这一句即可,其它不用修改

**Comment by chenliming777** [comment]
好的   了解了  谢谢
