### ISSUE TITLE
pod insatll can not find header file

### ISSUE THREAD

**Issue by zhangjiyong** [chenliming777/LMLiveStreaming#9]
新建工程引入pod 'LFLiveKit', '~> 1.6'，pod update 之后 build 工程
"openssl/bn.h" file not found
Could not build module "pill_librtmp"

**Comment by zhangjiyong** [comment]
error：GPUImage/GLProgram.h file not found  
could not module "LMGPUImae

why?

**Comment by chenliming777** [comment]
you can try pod repo update

**Comment by zhangjiyong** [comment]
当podfile 使用use_frameworks! 时 使用pod 'LFLiveKit' 就会报错，但是工程需要依赖use_frameworks!，怎么破

**Comment by chenliming777** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
use_frameworks!

target "LMLiveStreaming" do

pod 'LFLiveKit', '~> 1.6.3'

end
这样没有问题呀

**Comment by chenliming777** [comment]
你的pod file   给我看下  我测测

**Comment by zhangjiyong** [comment]
platform :ios, '8.0'

use_frameworks!

target "ComTest" do
pod 'Masonry'
pod 'ReactiveCocoa', '~> 4.1.0'
pod 'LFLiveKit', '~> 1.6.3'
end

**Comment by chenliming777** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

target "LMLiveStreaming" do
pod 'Masonry'
pod 'ReactiveCocoa', '~> 4.1.0'
pod 'LFLiveKit', '~> 1.5.2'
end

**Comment by chenliming777** [comment]
这样你在试一下

**Comment by zhangjiyong** [comment]
<img width="935" alt="2016-07-13 11 10 24" src="https://cloud.githubusercontent.com/assets/18301485/16790723/c46c5f36-48ea-11e6-9bb8-a5c17d558f33.png">

**Comment by chenliming777** [comment]
你qq号发我邮箱详细聊一下   这样太费劲了

**Comment by zhangjiyong** [comment]
已发送

**Comment by chenliming777** [comment]
https://github.com/LaiFengiOS/LFLiveKit/issues/18
